apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "gke-server"
  namespace: "default"
  labels:
    app: "hello"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "hello"
  template:
    metadata:
      labels:
        app: "hello"
    spec:
      containers:
      - name: "sample-name-1"
        image: "europe-west4-docker.pkg.dev/www-server-resume-1/www-server/sample-name:latest"