apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "gke-server"
  namespace: "default"
  labels:
    app: "hello"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "hello"
  template:
    metadata:
      labels:
        app: "hello"
    spec:
      containers:
      - name: "sample-name-1"
        image: "LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE@DIGEST"
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
