apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-app
        image: europe-west4-docker.pkg.dev/www-server-resume-1/www-server/sample-name:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
---
